#!/usr/bin/env python3
"""render_state_map — render one hs-run domain's states into a per-skill STATE.md.

ONE direction only: registry SSOT -> view. The renderer never edits the registry.
Same contract as render_standards.py, which this follows deliberately rather than
inventing a second shape: deterministic (no timestamp, no randomness, states in the
registry's own order), idempotent, a generated-marker header, and a `--check` mode
that renders in memory and diffs so CI can fail on drift without writing anything.

WHY A SEPARATE FILE RATHER THAN A LONGER SKILL BODY

The skill body and the envelope both speak to a model mid-run. `next_action` answers
"what do I do now"; it cannot answer "what is this machine, and what comes after the
step I am on" because it only ever describes one state. A reader needs that second
answer BEFORE running anything, and paying for it on every envelope would put index
prose into every run that fires the state.

WHY THE STATE LIST COMES FROM THE EMITTER

`step_routing` is not the source of truth for WHICH states exist — it is the source
for what each state ROUTES. Several states route nothing and are right to: their
`next_action` says all there is to say, and they carry only a summary sentence. A
renderer walking `states:` would produce a map that agrees with its input perfectly
while omitting states a user really lands on. So the emitter is scanned for its state
literals, and the registry supplies each one's sentence.

CLI:
    render_state_map.py --root <project-dir> --domain <name> --out <path>
                        [--force] [--check]
        --domain REQUIRED. The hs-run domain (currently: plan).
        --out    REQUIRED. No implicit default: rendering over a hand-authored file
                 would silently wipe it, and the output path sits inside a skill
                 directory where hand-authored markdown is the norm.
        --force  overwrite an --out file that lacks the generated-marker.
        --check  render in memory and diff against --out; exit 1 on any drift,
                 0 if identical. Never writes.
"""

import argparse
import ast
import sys
from pathlib import Path
from typing import Dict, List, Optional

import diff_render
from encoding_utils import configure_utf8_console
from verb_result_shapes import result_literals, states_named

configure_utf8_console()


# `# learn:` is the repo-wide escape hatch for a line that CITES a path to teach rather
# than narrating a mechanism at the model. Needed here because both lines below name the
# registry, which USR-AR-A2 catches on purpose: a SKILL.md has no business telling the
# model that a registry exists. This file is the opposite case — it is generated, nobody
# reads it mid-run, and a reader who does not know where the sentences come from will
# edit the render and lose the edit on the next one. Dropping the path to go green would
# remove the only thing that prevents that.
GENERATED_MARKER = (
    "<!-- generated by render_state_map.py — edit the SSOT, # learn: "
    "\"${HARNESS_BIN_ROOT:-.}\"/harness/data/hs-run-registry.d/<domain>.yaml, "
    "not this file -->"
)

def _known_domains():
    """Domains the registry declares a verb module for."""
    import hs_run
    return [d for d, verbs in (hs_run.load_registry() or {}).items()
            if any((s or {}).get("module") for s in (verbs or {}).values())]


def _emitter_for(root: Path, domain: str):
    """The module file that owns `domain`'s verbs, read from the registry.

    This was a hand-kept table, and enrolment in it was a step someone had to remember:
    a domain could opt into `covers_skill`, pass every routing gate, and still have no
    state map, because the map's own gate only checks domains the table names. The
    registry already answers the question — every verb declares its module — so the
    table was a second, less reliable copy of it.

    A domain with verbs across two modules is not something the registry forbids and
    not something this renderer can express; it takes the module the first verb names
    and would under-report the rest. No domain is shaped that way today, and the
    coverage test above fails loudly the day one is.
    """
    import hs_run
    verbs = (hs_run.load_registry() or {}).get(domain) or {}
    for spec in verbs.values():
        mod = (spec or {}).get("module")
        if mod:
            return "%s.py" % mod
    raise KeyError(domain)

def emitted_states(root: Path, domain: str) -> List[str]:
    """State names the domain's module can emit, in first-appearance order.

    Source order rather than alphabetical: the emitter is written in roughly the
    order a run walks, so the map reads as a path instead of a dictionary.

    Parsed, not matched. This scanned for the text `"state": "..."` on the stated
    ground that "the envelope is built from dict literals ... measured on
    hs_run_plan.py: zero such sites, all 26 are literals" — a claim that was true
    when written and stopped being true when the module moved onto
    `StepResult(state=...)`. The regex then found NOTHING, and the renderer
    happily produced a map missing 22 of 26 rows: a generated file that documents
    a quarter of the domain and says nothing about the rest is worse than no map,
    because it reads as complete.

    Read through `verb_result_shapes`, the one module that answers "what shape is
    a verb result" — NOT a private copy of the walk. This file did keep a private
    copy, and it fell exactly one question behind: it could not resolve a state
    assigned to a local, so `plan graph`'s four states never reached the map. The
    gate over this renderer had its own copy of the same too-narrow walk, so the
    two agreed perfectly and `--check` reported the map in sync while four rows
    were missing. Three readers asking the same wrong question do not disagree,
    and their agreement was being read as proof.

    A state assembled from anything other than a same-function literal assignment
    is still invisible; that limit is real, and it is why the map's claim is about
    the literal vocabulary."""
    text = (root / "harness" / "scripts"
            / _emitter_for(root, domain)).read_text(encoding="utf-8")
    tree = ast.parse(text)

    # Sorted by position so "first appearance" keeps meaning what it says —
    # `ast.walk` yields breadth-first, which would order the rows by nesting
    # depth and quietly reshuffle the map on every render.
    hits = []
    for fn in ast.walk(tree):
        # Per FUNCTION, because resolving a local is only sound inside the scope
        # that assigned it — a module-wide lookup would pull a same-named local
        # out of an unrelated function and invent a state nothing emits.
        if not isinstance(fn, ast.FunctionDef):
            continue
        for node, fields in result_literals(fn):
            # `states_named` returns a SET, and one result carrying several states
            # gives them all the same position — so the sort below cannot separate
            # them and the tie is broken by set iteration order, which varies with
            # PYTHONHASHSEED. Measured: four different row orders on four seeds,
            # i.e. a "generated" file whose bytes depend on the interpreter's hash
            # salt, and a --check gate that fails at random in CI. Sorting the tie
            # by name makes the position sort total.
            for name in sorted(states_named(fields, scope=fn)):
                hits.append(((node.lineno, node.col_offset, name), name))
    seen: List[str] = []
    for _pos, name in sorted(hits, key=lambda h: h[0]):
        if name not in seen:
            seen.append(name)
    return seen


def registry_states(root: Path, domain: str) -> Dict[str, dict]:
    """Each state's normalized routing row, read through the CLI's own loader.

    Through `hs_run.load_step_routing()` rather than a local `yaml.safe_load` on
    purpose. A second parser is a second reader of the same file, which is the exact
    defect this whole map exists to close: the two drift, and the one nobody runs is
    the one that lies. Going through the loader also means a `summary:` the loader
    would drop can never reach the render — if the field is not declared on
    `StateRouting`, the map goes blank rather than quietly rendering from a channel
    the CLI cannot see."""
    scripts = str(root / "harness" / "scripts")
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    import hs_run

    # No `path=` argument. `load_step_routing(path)` names the ROOT registry file, and
    # the per-domain rows live in the `hs-run-registry.d/` fragments beside it, which
    # the loader resolves itself. Handing it the root file suppresses the fragment
    # merge and returns a routing table with zero states — silently, no exception —
    # so the render would come out structurally valid and completely empty. Measured
    # while writing this: 0 states with the argument, 26 without.
    block = (hs_run.load_step_routing() or {}).get(domain) or {}
    return block.get("states") or {}


def _cell(text: Optional[str]) -> str:
    """A table cell: single-line, pipes escaped. YAML folded scalars arrive with
    embedded newlines, which would break the row in half.

    `Optional` because the body was always written to absorb a missing summary — the
    annotation said `str` and the callers pass `row.get("summary")`, so the signature
    was the thing that was wrong. Widening it here rather than guarding at the two call
    sites keeps the empty-cell handling in one place; a state with no summary renders
    as a blank cell, and the gate that a summary must EXIST is a test, not this."""
    return " ".join(str(text or "").split()).replace("|", "\\|")


def render(root: Path, domain: str) -> str:
    states = registry_states(root, domain)
    emitted = emitted_states(root, domain)

    routed = [s for s in emitted if (states.get(s) or {}).get("refs")
              or (states.get(s) or {}).get("rules")
              or (states.get(s) or {}).get("docs")]
    bare = [s for s in emitted if s not in routed]

    lines: List[str] = [
        "# `hs-run %s` — state map" % domain,
        "",
        GENERATED_MARKER,
        "",
        "Every state `hs-run %s` can report, with what it means. Run the CLI, read the "
        "`state`, do the judgment that state names, run it again — each state is "
        "re-derived from artifacts on disk, so deleting an artifact regresses the state." % domain,
        "",
        # Bin-root form, not a project-relative path. Under a global install the harness
        # tree lives at $HARNESS_BIN_ROOT while the project keeps only its own data, so a
        # bare `harness/...` here would send the reader to a directory that does not exist
        # on their machine. Enforced by test_agent_bin_root_reads, which caught exactly
        # this line.
        # The path a reader needs sits in the marker comment above, which already carries
        # the `# learn:` citation prefix. Repeating it in visible prose would mean either a
        # second `# learn:` — a tooling artifact in a sentence written for a person — or an
        # unprefixed path, which USR-AR-A2 catches. One citation, in the line HTML hides.
        "This file is generated. Change the source named in the comment above, then "
        "re-render with `render_state_map.py`; edits made here are lost on the next "
        "render.",
        "",
        "## States that route something",
        "",
        "The CLI hands these rule and reference paths over at the moment the step "
        "begins — the body does not repeat them.",
        "",
        "| state | what it means | routes |",
        "|---|---|---|",
    ]
    for name in routed:
        row = states.get(name) or {}
        pointers = list(row.get("rules") or []) + list(row.get("refs") or []) + list(row.get("docs") or [])
        lines.append("| `%s` | %s | %s |" % (
            name, _cell(row.get("summary")),
            ", ".join("`%s`" % p for p in pointers) or "—"))

    lines += [
        "",
        "## States that route nothing",
        "",
        "Not a gap: each is fully served by the `next_action` line the envelope "
        "already carries, and needs no extra file to act on.",
        "",
        "| state | what it means |",
        "|---|---|",
    ]
    for name in bare:
        lines.append("| `%s` | %s |" % (name, _cell((states.get(name) or {}).get("summary"))))

    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".", help="project root")
    ap.add_argument("--domain", default=None, help="REQUIRED hs-run domain (e.g. plan)")
    ap.add_argument("--out", default=None, help="REQUIRED output path")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an --out file that lacks the generated-marker")
    ap.add_argument("--check", action="store_true",
                    help="diff rendered output against --out; exit 1 on drift, never write")
    args = ap.parse_args(argv)

    if not args.domain:
        sys.stderr.write("error: --domain is required (known: %s)\n"
                         % ", ".join(sorted(_known_domains())))
        return 2
    if not args.out:
        sys.stderr.write(
            "error: --out is required (no default — rendering over a hand-authored "
            "file would wipe it)\n")
        return 2

    root = Path(args.root).resolve()
    out_path = Path(args.out)
    if out_path.is_dir():
        sys.stderr.write("error: --out is a directory: %s\n" % out_path)
        return 2
    try:
        rendered = render(root, args.domain)
    except KeyError:
        sys.stderr.write("error: no verb module for domain %r (known: %s)\n"
                         % (args.domain, ", ".join(sorted(_known_domains()))))
        return 2

    if args.check:
        if not out_path.exists():
            sys.stderr.write("error: --check target does not exist: %s\n" % out_path)
            return 1
        current = out_path.read_text(encoding="utf-8")
        if current != rendered:
            sys.stderr.write("drift: %s is out of date — re-render from the SSOT\n" % out_path)
            sys.stderr.write(diff_render.render_check_diff(rendered, current, str(out_path)))
            return 1
        return 0

    if out_path.is_file() and not args.force:
        existing = out_path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            sys.stderr.write(
                "error: %s exists and is not a generated map (no marker); "
                "pass --force to overwrite\n" % out_path)
            return 2

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    sys.stdout.write(str(out_path) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
