from typing import Any, Protocol

from contract_ocr.domain.entities import Page


class PdfExtractor(Protocol):
    def open(self, path: str) -> Any: ...
    def extract(self, page: Any, document_id: str) -> Page: ...
    def evidence(self, page: Any) -> tuple[int, int, int, float]: ...


class Renderer(Protocol):
    def render(self, page: Any, dpi: int) -> Any: ...


class Preprocessor(Protocol):
    def apply(self, image: Any, steps: list[str]) -> tuple[Any, Any]: ...
    def restore(self, lines: list, transform: Any, shape: tuple, original_shape: tuple) -> None: ...
